server:
  port: 8021
spring:
  #给项目来个名字
  application:
    name: rabbitmq-provider
  #配置rabbitMq 服务器
  rabbitmq:
    host: 192.168.1.173
    port: 5672
    username: guest
    password: guest
    publisher-returns: true
  publisher-confirms: true